/*
 * DatabaseService, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ListApiCli.Api;
using ListApiCli.Model;
using ListApiCli.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ListApiCli.Test.Model
{
    /// <summary>
    ///  Class for testing ToDoItems
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ToDoItemsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ToDoItems
        //private ToDoItems instance;

        public ToDoItemsTests()
        {
            // TODO uncomment below to create an instance of ToDoItems
            //instance = new ToDoItems();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ToDoItems
        /// </summary>
        [Fact]
        public void ToDoItemsInstanceTest()
        {
            // TODO uncomment below to test "IsType" ToDoItems
            //Assert.IsType<ToDoItems>(instance);
        }


        /// <summary>
        /// Test the property 'ToDoItemsId'
        /// </summary>
        [Fact]
        public void ToDoItemsIdTest()
        {
            // TODO unit test for the property 'ToDoItemsId'
        }
        /// <summary>
        /// Test the property 'Details'
        /// </summary>
        [Fact]
        public void DetailsTest()
        {
            // TODO unit test for the property 'Details'
        }
        /// <summary>
        /// Test the property 'Deadline'
        /// </summary>
        [Fact]
        public void DeadlineTest()
        {
            // TODO unit test for the property 'Deadline'
        }
        /// <summary>
        /// Test the property 'IsDone'
        /// </summary>
        [Fact]
        public void IsDoneTest()
        {
            // TODO unit test for the property 'IsDone'
        }

    }

}
